server:
  port: 9981

# redis连接配置
spring:
  redis:
    host: 192.168.1.228
    port: 6379
    password: openpay123
    timeout: 60000
    jedis:
      pool:
        maxActive: 8
        maxIdle: 8
        minIdle: 0
        max-wait: 5000
    database: 1 # 指定数据库1
